package entity;
// Generated 6/11/2019 04:07:07 PM by Hibernate Tools 4.3.1



/**
 * Materia generated by hbm2java
 */
public class Materia  implements java.io.Serializable {


     private int idMateria;
     private Alumno alumno;
     private String nombreMateria;

    public Materia() {
    }

    public Materia(int idMateria, Alumno alumno, String nombreMateria) {
       this.idMateria = idMateria;
       this.alumno = alumno;
       this.nombreMateria = nombreMateria;
    }
   
    public int getIdMateria() {
        return this.idMateria;
    }
    
    public void setIdMateria(int idMateria) {
        this.idMateria = idMateria;
    }
    public Alumno getAlumno() {
        return this.alumno;
    }
    
    public void setAlumno(Alumno alumno) {
        this.alumno = alumno;
    }
    public String getNombreMateria() {
        return this.nombreMateria;
    }
    
    public void setNombreMateria(String nombreMateria) {
        this.nombreMateria = nombreMateria;
    }




}


