/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package InterfazCte;

import Objetos.Cliente;
import Objetos.Cuenta;
import java.io.IOException;
import java.io.ObjectInputStream;
import java.io.ObjectOutputStream;
import java.net.Socket;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author jonat
 */
public class CajeroATM extends javax.swing.JFrame {

    Integer nameUser;
    String password;
    ObjectInputStream ois;
    ObjectOutputStream oos;
    Cliente clienteActual = new Cliente();
    Cuenta cuentaToRet = new Cuenta();

    /**
     * Creates new form NewJFrame1
     */
    public CajeroATM() throws IOException, ClassNotFoundException {
        try {
            nameUser = Integer.parseInt(JOptionPane.showInputDialog("ID usuario: "));
            password = JOptionPane.showInputDialog("Contraseña: ");
            System.out.println("ddddddddffffff");
            Socket clienteSocket = null;
            int port = 8001;
            clienteSocket = new Socket("localhost", port);

            oos = new ObjectOutputStream(clienteSocket.getOutputStream());
            ois = new ObjectInputStream(clienteSocket.getInputStream());//se instancia unflujo deObjeto de salida (para enviar objetos serializados a través de el)

            clienteActual.setIdcliente(nameUser);
            clienteActual.setContrasenia(password);

            System.out.println("writing objt");
            oos.writeObject(1);
            oos.writeObject(clienteActual);

            Object respuestaServer = ois.readObject();

            if (respuestaServer instanceof Cliente) {
                clienteActual = (Cliente) respuestaServer;
                if (password.equals(clienteActual.getContrasenia())) {
                    System.out.println(clienteActual.getNombre());
                    System.out.println("Aceptado");
                    initComponents();
                }
            }
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(null, "El dato es es núm. entero");

        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();

        jButton1.setText("jButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Cajero ATM RED");
        setBackground(new java.awt.Color(204, 255, 204));
        setBounds(new java.awt.Rectangle(0, 0, 0, 0));
        setFont(new java.awt.Font("Roboto", 0, 10)); // NOI18N

        jLabel1.setFont(new java.awt.Font("Roboto Black", 0, 21)); // NOI18N
        jLabel1.setText("Cajero ATM");

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/servicios_red.png"))); // NOI18N

        jButton2.setBackground(new java.awt.Color(255, 204, 204));
        jButton2.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/strongbox(1).png"))); // NOI18N
        jButton2.setText("Consulta de saldo");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setBackground(new java.awt.Color(204, 255, 204));
        jButton3.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/piggy-bank.png"))); // NOI18N
        jButton3.setText("Depósito");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setBackground(new java.awt.Color(255, 153, 255));
        jButton4.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/cash.png"))); // NOI18N
        jButton4.setText("Transferencia");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.setBackground(new java.awt.Color(255, 255, 153));
        jButton5.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/get-money.png"))); // NOI18N
        jButton5.setText("Retiro");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jButton6.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        jButton6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/logout.png"))); // NOI18N
        jButton6.setText("Salir");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButton6))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(52, 52, 52)
                        .addComponent(jLabel1)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(jButton5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1))
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2)
                    .addComponent(jButton3))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton6)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        try {
            // TODO add your handling code here:

            Double cantidad = Double.parseDouble(JOptionPane.showInputDialog("Cantidad:"));
            Long noCta = Long.parseLong(JOptionPane.showInputDialog("De la cuenta:"));
            Long noCta2 = Long.parseLong(JOptionPane.showInputDialog("Para la cuenta:"));
            cuentaToRet.setIdcuenta(noCta);
            cuentaToRet.setCliente(clienteActual);
            System.out.println(cuentaToRet);

            oos.writeObject(5);
            oos.writeObject(cuentaToRet);
            oos.writeObject(new Cuenta(noCta2, 0, null));

            oos.writeObject(cantidad);

            if ((Boolean) ois.readObject()) {
                JOptionPane.showMessageDialog(null, "Retiro realizado");
            }

        } catch (IOException | ClassNotFoundException ex) {
            Logger.getLogger(CajeroATM.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        try {
            // TODO add your handling code here:
            int i;
            String auxCadena = "";
            oos.writeObject(2);
            oos.writeObject(this.clienteActual);
            ArrayList<Cuenta> clienteEnCuestion = (ArrayList<Cuenta>) ois.readObject();
            for (i = 0; i < clienteEnCuestion.size(); i++) {
                auxCadena = auxCadena.concat(Long.toString(clienteEnCuestion.get(i).getIdcuenta()) + ": ");
                auxCadena = auxCadena.concat(Double.toString(clienteEnCuestion.get(i).getBalance()) + " " + "$\n");
            }
            JOptionPane.showMessageDialog(null, "Su saldo es de: \n" + auxCadena);
        } catch (IOException | ClassNotFoundException ex) {
            Logger.getLogger(CajeroATM.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        try {
            // TODO add your handling code here:

            Double cantidad = Double.parseDouble(JOptionPane.showInputDialog("Cantidad:"));
            Long noCta = Long.parseLong(JOptionPane.showInputDialog("Cuenta:"));
            cuentaToRet.setIdcuenta(noCta);
            cuentaToRet.setCliente(clienteActual);
            System.out.println(cuentaToRet);

            oos.writeObject(3);
            oos.writeObject(cuentaToRet);

            oos.writeObject(cantidad);

            if ((Boolean) ois.readObject()) {
                JOptionPane.showMessageDialog(null, "Deposito realizado");
            }

        } catch (IOException | ClassNotFoundException ex) {
            Logger.getLogger(CajeroATM.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        try {
            // TODO add your handling code here:

            Double cantidad = Double.parseDouble(JOptionPane.showInputDialog("Cantidad:"));
            Long noCta = Long.parseLong(JOptionPane.showInputDialog("Cuenta:"));
            cuentaToRet.setIdcuenta(noCta);
            cuentaToRet.setCliente(clienteActual);
            System.out.println(cuentaToRet);

            oos.writeObject(4);
            oos.writeObject(cuentaToRet);

            oos.writeObject(cantidad);

            if ((Boolean) ois.readObject()) {
                JOptionPane.showMessageDialog(null, "Retiro realizado");
            }

        } catch (IOException | ClassNotFoundException ex) {
            Logger.getLogger(CajeroATM.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton5ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CajeroATM.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CajeroATM.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CajeroATM.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CajeroATM.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new CajeroATM().setVisible(true);
                } catch (IOException ex) {
                    Logger.getLogger(CajeroATM.class.getName()).log(Level.SEVERE, null, ex);
                } catch (ClassNotFoundException ex) {
                    Logger.getLogger(CajeroATM.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
